apiVersion: v1
kind: Namespace
metadata:
  name: asdasasdaj-staging
  labels:
    environment-id: env_99a5259d-e020-48cf-bab6-13c800945efc
    project-id: project_a71f4cb3-b6b4-40b2-a075-280d96e57459
    project-name: asdasasdaj
    environment-name: staging
    organization-id: org_99bfadb5-996a-47d5-a5fc-442c14a28627
